### ISSUE TITLE
Models test example no longer working with redux-orm 0.8

### ISSUE THREAD

**Issue by bbbouvier** [tommikaikkonen/redux-orm-primer#1]
First of all, thank you for your really detailed examples. Really helpful.

I've faced a problem though when I reached the unit testing part. I started by testing with bootstrapping state with my own data, but factories are pretty cool and fast way to get it done.

I've setup everything properly, used your ReduxORMAdapter for the factory. 

```
//testModels.js
factory.createMany('User', 2).then(users => {});
```

The line above reaches the "build" method of the adapter which call "Model.create(props);"

```
//utils.js
export class ReduxORMAdapter {
    build(Model, props) {
        return Model.create(props);
    }
}
```

But in redux-orm v0.8 the "Model.create" method try to access "this.session" (l.476) which is undefined

```
//redux-orm/lib/Model.js
        key: 'markAccessed',
        value: function markAccessed() {
            this.session.markAccessed(this); //this.session is undefined
        }
```

I've tested with redux-orm v0.5.1, everything works correctly.

Do you have any idea why this.session is not initialized within Model class from modelsTests example?

**Comment by tommikaikkonen** [comment]
Looks like I was depending on an undocumented quirk to set up the factories (global Model objects without a Session instance) that I removed later. Fixed that along with updating packages and using `redux-orm-proptypes` for validation here https://github.com/tommikaikkonen/redux-orm-primer/commit/0091079dc3c32f12ac090b54392c33fe4bc2a24e

**Comment by bbbouvier** [comment]
Works like a charm! Thanks a lot!
